import type { Metadata } from "next";

import "./globals.css";
import Header from "./_components.tsx/Header";
import { LoadingProvider } from "./context/LoadingContext";

export const metadata: Metadata = {
  title: "Podcast Zara",
  description: "Generated by Cesar Samuel",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="container mx-auto">
        <LoadingProvider>
          <Header />
          <div className="mb-10">{children}</div>
        </LoadingProvider>
      </body>
    </html>
  );
}
